---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation for create bastion'

#Paramentes
Parameters:
  VpcID:
    Description: VPC for EC2
    Type: AWS::EC2::VPC::Id
    Default: "vpc-0707f4776dfb2d9a7"
  SubNetId:
    Description: Subnet for EC2
    Type: AWS::EC2::Subnet::Id
    Default: "subnet-0d7f74cb8360bcffd"
  SecurityGroupName:
    Description: SG for EC2
    Type: AWS::EC2::SecurityGroup::GroupName
    Default: "SG-BASTION-InstanceSecurityGroup-1UGUU3F2MF4JF"
  KeyName:
    Description: KeyPair for EC2
    Type: AWS::EC2::KeyPair::KeyName
    Default: bastion-key
  InstanceType:
    Description: EC2 Type
    Type: String
    Default: t2.micro
  Region:
    Description: Region
    Type: String
    Default: us-east-1
Mappings:
  AWSInstanceType2Arch:
      t1.micro:
       Arch: HVM64
      t2.nano:
        Arch: HVM64
      t2.micro:
        Arch: HVM64
  AWSRegionArch2AMI:
      us-east-1:
        HVM64: ami-0080e4c5bc078760e
        HVMG2: ami-0aeb704d503081ea6

#Resources
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId:
        Ref: VpcID
      SubnetId:
        Ref: SubNetId
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
      - Ref: SecurityGroupName
      KeyName:
        Ref: KeyName
      ImageId:
          Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - Fn::FindInMap:
            - AWSInstanceType2Arch
            - Ref: InstanceType
            - Arch
